"""Independent Claim B candidate known answers supplied by the consumer.

The word stream is assembled here from literal 7-series packet words.  It does not call
``icap_sequence.build_envelope`` or ``build_sequence``; the artifact under judgement is
therefore not generated by the producer code that parses it.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import frame_ecc as fe  # noqa: E402
import gate_candidate as gc  # noqa: E402

DUMMY = 0xFFFFFFFF
SYNC = 0xAA995566
NOOP = 0x20000000
WRITE_CMD_1 = 0x30008001
WRITE_IDCODE_1 = 0x30018001
WRITE_FAR_1 = 0x30002001
WRITE_FDRI_0 = 0x30004000
WRITE_CRC_1 = 0x30000001
TYPE2_WRITE_202 = 0x400000CA
RCRC = 0x00000007
WCFG = 0x00000001
DESYNC = 0x0000000D
IDCODE = 0x03722093
TARGET_FAR = 0x00400A20
FLUSH_FAR = 0x00400A21


def manifest() -> dict:
    zero = ["0x00000000"] * 101
    return {
        "base_bitstream": {"idcode": f"0x{IDCODE:08X}"},
        "frames": [
            {"far": f"0x{TARGET_FAR:08X}", "role": "target", "words": zero},
            {"far": f"0x{FLUSH_FAR:08X}", "role": "flush", "words": zero},
        ],
        "ownership": {
            "whitelist_by_far": {
                f"0x{TARGET_FAR:08X}": [{"word": 51, "bit": 0}]
            }
        },
        "write_envelope": {
            "envelopes": [
                {
                    "far_set": f"0x{TARGET_FAR:08X}",
                    "target_fars": [f"0x{TARGET_FAR:08X}"],
                    "flush_far": f"0x{FLUSH_FAR:08X}",
                    "payload_words": 202,
                }
            ]
        },
    }


def independent_envelope(target: list[int], flush: list[int]) -> list[int]:
    """The fixed 31-word-overhead shape, encoded without producer builder helpers."""
    return (
        [DUMMY] * 8
        + [
            SYNC,
            NOOP,
            WRITE_CMD_1,
            RCRC,
            NOOP,
            NOOP,
            WRITE_IDCODE_1,
            IDCODE,
            WRITE_CMD_1,
            WCFG,
            NOOP,
            WRITE_FAR_1,
            TARGET_FAR,
            WRITE_FDRI_0,
            TYPE2_WRITE_202,
        ]
        + target
        + flush
        + [WRITE_CRC_1, 0, WRITE_CMD_1, DESYNC, NOOP, NOOP, NOOP, NOOP]
    )


class IndependentCandidateKnownAnswers(unittest.TestCase):
    def test_literal_fixture_is_the_pinned_envelope_size(self) -> None:
        words = independent_envelope([0] * 101, [0] * 101)
        self.assertEqual(len(words), 233)

    def test_correct_ecc_does_not_authorise_out_of_whitelist_content(self) -> None:
        target = [0] * 101
        target[51] = 0x00000002  # bit 1; only bit 0 is whitelisted
        target[50] = 0x000009C1  # independently pinned known answer for that edit
        self.assertTrue(fe.frame_is_consistent(target), "fixture ECC is not actually valid")
        verdict = gc.gate_candidate(manifest(), [independent_envelope(target, [0] * 101)])
        self.assertFalse(verdict["writable"])
        self.assertEqual(verdict["buckets"]["target_frame"], 1)
        self.assertEqual(verdict["buckets"]["ecc"], 0)

    def test_the_same_legal_target_edit_is_illegal_in_a_flush_frame(self) -> None:
        target = [0] * 101
        target[51] = 0x00000001
        target[50] = 0x000019C0
        self.assertTrue(fe.frame_is_consistent(target))
        accepted = gc.gate_candidate(manifest(), [independent_envelope(target, [0] * 101)])
        self.assertTrue(accepted["writable"], accepted["findings"])

        refused = gc.gate_candidate(manifest(), [independent_envelope([0] * 101, target)])
        self.assertFalse(refused["writable"])
        self.assertEqual(refused["buckets"]["flush_frame"], 1)


if __name__ == "__main__":
    unittest.main()
