#!/usr/bin/env python3
"""B2 — render the gate report (evidence/b2/gate/gate_report.json) as docs/b2_gate_report.md.
Every number in the Markdown comes from the JSON; nothing is typed by hand."""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "host"))
import b2_gate as bg  # noqa: E402

SRC = REPO_ROOT / "evidence/b2/gate/gate_report.json"
DST = REPO_ROOT / "docs/b2_gate_report.md"
TEXT = {"G1": "non-saturation", "G2": "not a definitional lock", "G3": "shuffled map does not profit", "G4": "oracle headroom",
        "G5": "effect, power, N, session cost", "G6": "no fixed-seed lock", "G7": "dose–response", "G8": "not LUT membership",
        "budget_rule": "budget rule"}


def f(x, nd=2):
    if x is None:
        return "—"
    if isinstance(x, bool):
        return "yes" if x else "no"
    if isinstance(x, float):
        return f"{x:.{nd}f}"
    return str(x)


def render(r: dict) -> str:
    o = []
    src_note = ""
    if r.get("schema") == "b2_gate_recomputation":
        src_note = (f" **A recomputation** (`{r['label']}`) of the rows of `{r['source']['path']}` (report sha256 `{r['source']['gate_report_sha256'][:12]}…`, "
                    f"seeds master {r['source']['seeds']['master_seed']}, run under rules {r['source']['rules_version_at_source']}); the source report is untouched.")
        r = dict(r, seeds=r["source"]["seeds"], worktree_dirty_at_start=False, engine={"version": "b2-es-v1", "mu": 4, "lambda": 8, "kmax": 4},
                 maps={"self_map": {"sha256": "c6a4b23e1871e1889621191d671886f804c88edaa9748119d9a5006fd0b64296", "path": "evidence/b1/b1_17A6_2026-09-08-02/self_map_v2.json"},
                       "oracle": {"sha256": "57aaa412b560ea7b88d9d9015234461016ff6ccb9e9fc0d45b065695ab9bc412", "relations_agree_with_self_map": [292, 292]}})
    o.append(f"# B2 — discriminability gate report (rules {r['thresholds']['rules_version']}, host simulation, {r['generated_utc'][:10]})\n")
    if src_note:
        o.append(">" + src_note + "\n")
    o.append("> **Standing: a host simulation over the fabric model; no board contact.** Generated by "
             "`host/b2_gate_report_md.py` from `evidence/b2/gate/gate_report.json`; every number below is that file's. "
             f"Rules: `docs/b2_architecture.md` §7 (sha256 `{r['architecture']['sha256'][:12]}…`, last changed in commit "
             f"`{(r['architecture']['last_commit'] or '')[:7]}`). Run at HEAD `{(r['head_at_run'] or '')[:7]}`, "
             f"worktree dirty at start: {f(r['worktree_dirty_at_start'])}. Seeds: {r['seeds']['count']} landscapes, master "
             f"{r['seeds']['master_seed']} ({r['seeds']['derivation']}). Engine `{r['engine']['version']}` "
             f"(μ = {r['engine']['mu']}, λ = {r['engine']['lambda']}, k ≤ {r['engine']['kmax']}). Self-map "
             f"`{r['maps']['self_map']['sha256'][:12]}…` ({r['maps']['self_map']['path']}); oracle rendering "
             f"`{r['maps']['oracle']['sha256'][:12]}…`; relations agreeing: "
             f"{r['maps']['oracle']['relations_agree_with_self_map'][0]}/{r['maps']['oracle']['relations_agree_with_self_map'][1]}.\n")
    o.append(f"**Selection rule** (§7, frozen order {' → '.join(r['selection_order'])}): the first fitness passing every "
             f"criterion is **{r['selected_fitness'] or 'none'}**.\n")
    o.append("## 1. Verdict per fitness\n")
    o.append("| fitness | ceiling | B* | " + " | ".join(k for k in ("budget_rule", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8")) + " | PASS |")
    o.append("|---|---|---|" + "---|" * 9 + "---|")
    for fid in r["selection_order"]:
        x = r["results"].get(fid)
        if not x:
            continue
        cells = []
        for k in ("budget_rule", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8"):
            c = x["criteria"].get(k)
            cells.append("—" if c is None else ("PASS" if c["pass"] else "FAIL"))
        o.append(f"| {fid} | {x['ceiling']} | {f(x['b_star'])} | " + " | ".join(cells) + f" | **{'PASS' if x['pass'] else 'FAIL'}** |")
    o.append("")
    for fid in r["selection_order"]:
        x = r["results"].get(fid)
        if not x:
            continue
        o.append(f"## 2.{r['selection_order'].index(fid) + 1}. {fid} — median best-so-far train fitness by budget (S = {x['seeds']})\n")
        o.append("| arm | " + " | ".join(str(b) for b in x["grid"]) + " |")
        o.append("|---|" + "---|" * len(x["grid"]))
        for arm in bg.ARMS:
            o.append(f"| {arm} {bg.ARM_TEXT[arm]} | " + " | ".join(f(v, 1) for v in x["curves_median"][arm]) + " |")
        o.append("")
        if x.get("per_budget"):
            o.append("Arm B (self-map) minus arm A (random-safe), per budget:\n")
            o.append("| budget | mean Δ | Cohen's d | + / − / ties | sign-test p (S) | N(B) | cost N×2×B | G1 |")
            o.append("|---|---|---|---|---|---|---|---|")
            for t in x["per_budget"]:
                o.append(f"| {t['budget']} | {f(t['mean_delta_B'])} | {f(t['cohen_d_B'])} | {t['positives']} / {t['negatives']} / {t['ties']} | "
                         f"{t['sign_test_p_full_S']:.2e} | {f(t['required_pairs_N'])} | {f(t['session_evaluations'])} | {f(t['G1'])} |")
            o.append("")
        if x["b_star"] is None:
            o.append(f"No budget qualifies: {x['criteria']['budget_rule'].get('note')}\n")
            continue
        o.append(f"At B* = {x['b_star']}: medians " + ", ".join(f"{a} {f(v, 1)}" for a, v in x["at_b_star_median"].items()) +
                 "; mean Δ vs A " + ", ".join(f"{a} {f(v)}" for a, v in x["mean_delta_vs_A_at_b_star"].items()) +
                 "; champion holdout medians " + ", ".join(f"{a} {f(v, 1)}" for a, v in x["champion_holdout_median"].items()) + ".\n")
        o.append("| criterion | numbers | verdict |")
        o.append("|---|---|---|")
        for k in ("budget_rule", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8"):
            c = dict(x["criteria"][k])
            verdict = "PASS" if c.pop("pass") else "FAIL"
            c.pop("candidates", None); c.pop("signs_by_budget", None); c.pop("rule", None)
            nums = "; ".join(f"{kk} = {f(v, 3) if isinstance(v, float) else v}" for kk, v in c.items())
            o.append(f"| {k} {TEXT[k]} | {nums} | {verdict} |")
        o.append("")
    o.append("## 3. Reading\n")
    o.append("- On every fitness the self-map arm (B) beats random-safe (A), and the oracle arm (C) equals B exactly — "
             "B1's map is the certificate's mapping (292/292), so the two arms are the same operator on the same relations.")
    o.append("- The shuffled map (D) and the within-LUT-shuffled map (E) do **not** profit — their mean Δ is negative: a wrong map "
             "through the same move shape costs budget. The benefit is column identity, not LUT membership (G8).")
    o.append("- The dose–response is monotone in map quality and crosses zero between q = ½ and q = ¾: under the ½ mixture a poor "
             "map is worse than no map (`docs/b2_architecture.md` §8). This is a property of the operator, reported, not tuned away.")
    o.append("- Champion holdout medians are equal across arms: the search does not move holdout positions — holdout is a "
             "neutrality / known-answer control here, not a generalisation measure (§8).")
    o.append("- What separates the fitnesses is the **session cost** of a powered test (G5), not discrimination: the selected "
             "fitness is the first in the frozen order whose N(B*) × 2 × B* fits one two-hour session at the evidenced "
             "sampled-audit rate; whether it also fits the all-self-reporting rate is reported in G5 and is the owner's choice.")
    o.append("")
    return "\n".join(o)


def render_controls(c: dict) -> str:
    o = [f"\n## 4. The predeclared control comparison G9 (architecture v0.3 §7a; `{c['label']}`)\n",
         f"Run at HEAD `{(c['head_at_run'] or '')[:7]}`, worktree dirty at start: {f(c['worktree_dirty_at_start'])}; the same 200 seeds "
         f"and rows as the run above (master {c['source']['seeds']['master_seed']}). T = train-membership only, W = within-train column scramble; "
         f"both name 183 train / 0 holdout addresses (D and E named ~112 / ~71).\n",
         "| fitness | B* | control | median | Δ vs A | B − control | Cohen's d | + / − / ties | p (B > control) | fraction of B's benefit retained | G9 |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for fid, x in c["results"].items():
        for arm in ("T", "W"):
            v = x["arms"][arm]
            o.append(f"| {fid} | {x['b_star']} | {arm} {v['text']} | {f(v['median'], 1)} | {v['mean_delta_vs_A']:+.2f} | {v['mean_delta_B_minus_arm']:+.2f} | "
                     f"{f(v['cohen_d_B_minus_arm'])} | {v['positives']} / {v['negatives']} / {v['ties']} | {v['sign_test_p_B_gt_arm']:.1e} | "
                     f"{f(v['fraction_of_B_benefit_retained'], 3)} | {'PASS' if v['pass'] else 'FAIL'} |")
        o.append(f"| {fid} | | **G9** | | | | | | | | **{'PASS' if x['G9']['pass'] else 'FAIL'}** |")
    o.append("")
    o.append("Reading: neither control is required to lose to random-safe (T is slightly above A, W about at A); what G9 asks is whether "
             "correct grouping adds benefit beyond membership and beyond the size distributions — it does, on every fitness. "
             "The D / E result of §2 stands as 'a wrong map costs budget', not as the attribution.")
    return "\n".join(o)


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=str(SRC))
    ap.add_argument("--dst", default=str(DST))
    ap.add_argument("--controls", default=None, help="a controls_report.json to append as §4")
    a = ap.parse_args(argv)
    r = json.loads(Path(a.src).read_text())
    text = render(r)
    if a.controls:
        text += render_controls(json.loads(Path(a.controls).read_text()))
    Path(a.dst).write_text(text)
    print(a.dst)
    return 0


if __name__ == "__main__":
    sys.exit(main())
