#!/usr/bin/env python3
"""Generate `firmware/b1/p3_data.h` for the B1 image — the instrument's header WITHOUT the
operator tables (host-only; nothing here touches a board).

The B1 cartographer must not be linked with any LUT key, INIT index, polarity or group
table (`docs/autonomous_cartography_roadmap.md` §2, B1's leakage guards). The instrument's
`host/gen_firmware_data.py` renders the whitelist, the envelopes and the pinned base frames
from the phenotype manifest and then appends the two-operator image's map data
(`P3_LUT_KEYS`, `P3_LUT_LEN`, `P3_LUT_BITS`, `P3_MUTATION_BITS`, `P3_OPERATOR_DATA_SHA256`).
This generator reuses the instrument's renderer for the first part — the same bytes the
pinned image was built from, so p3_derive.c compiles unchanged — and CUTS everything from
the operator block on, adding the B1 universe digest instead. `tests/test_b1_leakage.py`
checks the header and the built image for the absent tables.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "host"))
import claimb_r1p_instrument as inst  # noqa: E402

OUT = REPO_ROOT / "firmware/b1/p3_data.h"
OPERATOR_MARKER = "/* L6 two-operator image: the map data behind the map-guided operator"
FORBIDDEN = ("P3_LUT_KEYS", "P3_LUT_LEN", "P3_LUT_BITS", "P3_MUTATION_BITS", "P3_OPERATOR_DATA_SHA256", "CLBLL_L.", "CLBLM_L.")


def render_b1(require_git: bool = True) -> str:
    inst.bind(inst.DEFAULT_ROOT, require_git=require_git)
    import gen_firmware_data as gfd  # noqa: E402
    import p3_gate as g  # noqa: E402
    import p3_genome as gn  # noqa: E402
    manifest = g.load_manifest()
    full = gfd.render(manifest)
    i = full.index(OPERATOR_MARKER)
    head = full[:i].rstrip("\n")
    # replace the generator's banner line and the operator-data provenance line
    head = head.replace("/* GENERATED by host/gen_firmware_data.py — do not edit.",
                        "/* GENERATED by host/gen_b1_data.py (zynq-fabricmap) — do not edit.\n"
                        " * B1 image: the instrument's data header WITHOUT the two-operator map tables.")
    lines = [l for l in head.split("\n") if not l.startswith(" * Operator data (local_map.json derivation)")]
    universe = gn.addresses_sha256(manifest)
    lines += ["",
              "/* B1 (stage B1 cartography): the cartographer knows the universe and nothing else about it.",
              " * No LUT key, INIT index, polarity or group table is compiled into this image. */",
              "#define B1_DATA_NO_OPERATOR_TABLES 1",
              f'#define B1_UNIVERSE_SHA256 "{universe}"',
              "", "#endif /* P3_DATA_H */", ""]
    text = "\n".join(lines)
    for f in FORBIDDEN:
        if f in text:
            raise RuntimeError(f"forbidden token {f!r} in the B1 header")
    return text


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="compare with the committed header instead of writing")
    ap.add_argument("--no-git", action="store_true")
    a = ap.parse_args(argv)
    text = render_b1(require_git=not a.no_git)
    if a.check:
        cur = a.out.read_text() if a.out.is_file() else ""
        if cur != text:
            print(f"STALE: {a.out} differs from the generator's output", file=sys.stderr)
            return 1
        print(f"fresh: {a.out} sha256 {hashlib.sha256(text.encode()).hexdigest()}")
        return 0
    a.out.write_text(text)
    print(f"wrote {a.out} sha256 {hashlib.sha256(text.encode()).hexdigest()} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
