"""The B3 application's audit (B3 lifecycle 2, image stage 5, first unit): its outbound buffers against the theoretical
maximum of what their encoders accept, the longest line through the instrument's own host reader and collector, the
fail-closed paths at the source, and the AXI allowlist against the carrier's RTL decode.

Bounds. A host driver GENERATED here (into the top-level build/, never under b3/) links the image's own encoders —
b3_record.c, b3_carto.c, b2_search.c, b3_wire.c, p3_derive.c — and calls each with every member present, every
integer at its widest and every string at the longest length the application can hand it (the longest string literal
of b3_app.c, p3_rectx.c and p3_pull.c — the reasons, the outcomes, the findings — or the fixed length of the hex
buffer it passes), and the O arm's search block at its LARGEST LEGAL ledger (all 384 positions toggled, all 292
addresses decoded at two-digit vectors, the widest counters). The bounds are recomputed from those measurements:
B3_SEARCH_BLOCK_MAX = the largest block + NUL; B3_PAYLOAD_MAX = the largest payload of any type + NUL; B3_ENCODED_MAX =
4 * ceil(payload / 3) + NUL; B3_LINE_MAX = "P3L5 " + the longest frame type + " " + 10 + " " + 32 + " " + the encoding +
" " + 8 + "\\n" + NUL — and b3_app.c must declare exactly those, and size every outbound and resend buffer with them.
Every encoder refuses (0) a buffer exactly its length and renders into one byte more.

The host side. The longest line the application can emit goes through the instrument's L6LineReader (the reader the
B1 / B2 sessions use) in pieces of every size, through l5_notary.parse_line / decode_payload, and — with seq 1 — through
the instrument's Collector; a torn first transmission is quarantined and the resend is the one line that counts.

The fail-closed paths are audited in the source (the dynamic exercise of the application is image stage 6's host
application): an encoder's 0 is PROTOCOL; the base64 capacity is checked BEFORE p3_base64url, which takes none; an
observation the orchestrator cannot complete, and a scored candidate whose block does not render, are PROTOCOL.

The AXI allowlist (the instrument's test_axi_map_vs_rtl, as tests/test_b1_carrier.py ports it): the application's
read and write decode lie inside rtl/b1/b1_axil.v's, the RTL's reads are all the application reads, the only RTL
writes the application lacks are the MAC key window, CTRL is never read and the key window is never named.

No skip: a missing compiler or instrument is a failure.
"""
from __future__ import annotations

import json
import math
import os
import re
import shutil
import subprocess
import sys
import unittest
from pathlib import Path

R = Path(__file__).resolve().parents[2]
for p in (R / "host", R / "b3/host"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))
import claimb_r1p_instrument as inst  # noqa: E402
import gen_b2_data as gen  # noqa: E402

FW = R / "b3/firmware"
APP = (FW / "b3_app.c").read_text()
RTL = (R / "rtl/b1/b1_axil.v").read_text()
KEY_WINDOW = frozenset(range(0x2160, 0x2170, 4))
BUILD = R / "build/b3_bounds"
TOKEN = "a13f38b53355fd4c1cac3145244727f8"
PAYLOAD_TYPES = ("REC", "IDENT", "SIGNREQ", "TERM", "AUDIT_READY", "AUDIT", "CLOSE", "HB", "AUDITWAIT")
BLOCK_TYPES = ("BLOCK_O_SEARCH", "BLOCK_O_HOLDOUT", "BLOCK_RF_SEARCH", "BLOCK_RF_HOLDOUT")
_CACHE: dict = {}

DRIVER = r'''/* GENERATED by b3/tests/test_b3_app_audit.py — the outbound-buffer bound driver (host only, never the image).
 * argv: <longest literal> <sparse entries> <line capacity> <token>. Prints "<NAME> <length> <exact> <plus1>" per
 * payload, then the longest framed REC line (seq 2^32-1) and the same record framed with seq 1 (for the collector). */
#include "b2_search.h"
#include "b3_carto.h"
#include "b3_record.h"
#include "b3_wire.h"
#include "p3_data.h"
#include "p3_derive.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char buf[1 << 20], blk[1 << 16], rec[1 << 17], enc[1 << 18], line[1 << 18];
static b2_search s;
static b3_carto c;
static uint16_t delta[B3_CARTO_POSITIONS], newly[B3_CARTO_N], bits[4] = {288, 289, 290, 291};

static char *str(size_t n, char ch)
{
    char *p = malloc(n + 1);
    memset(p, ch, n);
    p[n] = 0;
    return p;
}

#define PROBE(name, call_with_max) do { size_t n_ = call_with_max(sizeof(buf)); size_t a_ = call_with_max(n_); \
    size_t b_ = call_with_max(n_ + 1); printf("%s %lu %lu %lu\n", name, (unsigned long)n_, (unsigned long)a_, (unsigned long)b_); } while (0)

static b3_ledger_entry e;
static p3_wire_record_in r;
static p3_wire_identity_in id;
static p3_wire_summary_in sm;
static const char *lit, *h64, *h32, *h16, *g80, *entries;
static const char *kinds[1], *findings[8];
static const uint32_t sts[P3_ENVELOPE_COUNT] = {0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu};

static size_t o_search(size_t m) { return b3_record_json(&s, &c, INT_MAX, 0xFFFFFFFFu, -1, &e, m == sizeof(buf) ? blk : buf, m); }
static size_t o_holdout(size_t m) { return b3_record_json(&s, &c, INT_MAX, 0xFFFFFFFFu, INT_MAX, NULL, buf, m); }
static size_t rf_search(size_t m) { return b2_search_record_json(&s, INT_MIN, "B", 0xFFFFFFFFu, -1, buf, m); }
static size_t rf_holdout(size_t m) { return b2_search_record_json(&s, INT_MIN, "B", 0xFFFFFFFFu, INT_MAX, buf, m); }
static size_t w_rec(size_t m) { return p3_wire_loop_record(&r, m == sizeof(buf) ? rec : buf, m); }
static size_t w_ident(size_t m) { return p3_wire_identity(&id, buf, m); }
static size_t w_sign(size_t m) { return p3_wire_sign_request(h32, 0xFFFFFFFFu, 0xFFFFFFFFu, g80, 0xFFFFFFFFFFFFFFFFull, buf, m); }
static size_t w_term(size_t m) { return p3_wire_summary(&sm, buf, m); }
static size_t w_ready(size_t m) { return p3_wire_audit_ready(0xFFFFFFFFu, lit, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, buf, m); }
static size_t w_audit(size_t m) { return p3_wire_audit_sparse(0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, lit, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, entries, buf, m); }
static size_t w_close(size_t m) { return p3_wire_closing(0xFFFFFFFFFFFFFFFFull, 0xFFFFFFFFFFFFFFFFull, 0xFFFFFFFFu, 0xFFFFFFFFu, buf, m); }
static size_t w_hb(size_t m) { return p3_wire_hb(0xFFFFFFFFu, buf, m); }
static size_t w_wait(size_t m) { return p3_wire_audit_wait(0xFFFFFFFFu, 0xFFFFFFFFu, buf, m); }

int main(int argc, char **argv)
{
    size_t L = (size_t)strtoul(argv[1], NULL, 10), cap = (size_t)strtoul(argv[3], NULL, 10), n, k, plus;
    const char *token = argv[4];
    int i, kk, v, m = 0;
    (void)argc;
    lit = str(L, 'x'); h64 = str(64, 'f'); h32 = str(32, 'f'); h16 = str(16, 'f'); g80 = str(80, 'f');
    entries = str((size_t)strtoul(argv[2], NULL, 10), 'A');
    kinds[0] = lit;
    for (i = 0; i < 8; i++)
        findings[i] = lit;

    /* the O arm's search block at its largest legal ledger */
    b3_carto_init(&c);
    for (kk = 0; kk < B3_CARTO_LUTS && m < B3_CARTO_N; kk++)
        for (v = 10; v < B3_CARTO_VECTORS && m < B3_CARTO_N; v++)
            c.decoded[m++] = (int16_t)(kk * B3_CARTO_VECTORS + v);
    c.version = c.anomalies = 0xFFFFFFFFu;
    for (i = 0; i < B3_CARTO_POSITIONS; i++)
        delta[i] = (uint16_t)i;
    for (i = 0; i < B3_CARTO_N; i++)
        newly[i] = (uint16_t)(B3_CARTO_N - 1 - i);
    s.arm = 2;
    s.landscape_seed = s.operator_seed = s.budget = s.evals = s.generation = s.column_moves = 0xFFFFFFFFu;
    s.best = INT_MIN;
    for (i = 0; i < B2_MU; i++) {
        s.pop[i].fit = INT_MIN;
        s.pop[i].born = 0xFFFFFFFFu;
    }
    s.last_fit = B2_TRAIN_COUNT;
    s.last_kind = B2_MOVE_COLUMN;
    s.last_parent_born = 0xFFFFFFFFu;
    s.pending_nbits_last = 4;
    memcpy(s.last_bits, bits, sizeof(bits));
    e.seq = 0xFFFFFFFFu; e.map_version = 0xFFFFFFFEu; e.map_version_after = 0xFFFFFFFFu; e.anomalies = 0xFFFFFFFFu;
    e.parent_born = 0xFFFFFFFFu; e.fitness = B2_TRAIN_COUNT; e.kind = B2_MOVE_COLUMN; e.bits = bits; e.n_bits = 4;
    e.delta = delta; e.n_delta = B3_CARTO_POSITIONS; e.newly = newly; e.n_newly = B3_CARTO_N; e.carto = &c;
    PROBE("BLOCK_O_SEARCH", o_search);
    s.champion_done = 1;
    s.champion_holdout = INT_MAX;
    PROBE("BLOCK_O_HOLDOUT", o_holdout);
    s.champion_done = 0;
    s.arm = 1;
    s.last_fit = INT_MIN;
    PROBE("BLOCK_RF_SEARCH", rf_search);
    PROBE("BLOCK_RF_HOLDOUT", rf_holdout);

    /* the loop record: every member, the largest block */
    r.seq = 0xFFFFFFFFu; r.genome = g80; r.outcome = lit; r.audited = 0; r.search = blk; r.arm = B3_WIRE_ARM_RANDOM_SAFE;
    r.have_sign_refusal = 1; r.finding_kinds = kinds; r.finding_kinds_n = 1;
    r.have_sign_reply = 1; r.commit = h64; r.tag = h32;
    for (i = 0; i < 6; i++) {
        r.tables[i] = h16;
        r.readout[i] = h16;
        r.scores[i] = 0xFFFFFFFFu;
    }
    r.have_oracle = 1; r.staged_sha256 = r.staged_stream_sha256 = r.readback_sha256 = h64; r.envelopes_n = P3_ENVELOPE_COUNT;
    r.envelope_int_sts = sts; r.audit_available = 0;
    r.have_arm = 1; r.nonce_before = r.nonce_after = 0xFFFFFFFFFFFFFFFFull; r.status_after = r.fault_after = 0xFFFFFFFFu;
    r.key_loaded_observed = 0; r.writes_issued = INT_MIN; r.settle_polls = r.settle_polls_max = r.status_first = 0xFFFFFFFFu;
    r.settled = 0; r.have_audit_stop = 1; r.audit_stop_why = lit; r.audit_chunks_served = 0xFFFFFFFFu;
    r.have_sign_stop = 1; r.sign_stop_attempts = 0xFFFFFFFFu; r.sign_stop_why = lit;
    r.have_score = 1; r.hw_candidate_commit = h64; r.hb_before = r.hb_after = 0xFFFFFFFFu;
    PROBE("REC", w_rec);

    id.pss_idcode = id.uboot_epoch = id.status_at_start = id.fclk0_hz_decoded = id.app_epoch = 0xFFFFFFFFu;
    id.token = h32; id.carrier_sha256 = h64; id.nonce_at_start = 0xFFFFFFFFFFFFFFFFull; id.findings = findings; id.findings_n = 8;
    id.master_seed = 0xFFFFFFFFu; id.schedule_mode = B2_SEARCH_VERSION; id.operator_data_sha256 = h64; id.protocol = "rel-v4";
    id.universe_sha256 = h64; id.carrier_variant = 0xFFFFFFFFu; id.search_version = B2_SEARCH_VERSION; id.map_sha256 = h64;
    id.fitness_id = B2_FITNESS_ID; id.budget_per_arm = id.pairs_total = id.pair_first = id.pair_count = 0xFFFFFFFFu;
    id.carto_version = B3_CARTO_VERSION; id.arms = B3_WIRE_ARMS; id.b1_map_cost = 0xFFFFFFFFu;
    PROBE("IDENT", w_ident);
    PROBE("SIGNREQ", w_sign);
    sm.token = h32; sm.kind = lit; sm.reason = lit;
    sm.last_seq = sm.scored = sm.refused_by_gate = sm.audited = sm.total = sm.crc_dropped = sm.drop_budget = 0xFFFFFFFFu;
    sm.have_closing_control = 1; sm.close_nonce_before = sm.close_nonce_after = 0xFFFFFFFFFFFFFFFFull;
    sm.close_fault = sm.close_status = 0xFFFFFFFFu;
    PROBE("TERM", w_term);
    PROBE("AUDIT_READY", w_ready);
    PROBE("AUDIT", w_audit);
    PROBE("CLOSE", w_close);
    PROBE("HB", w_hb);
    PROBE("AUDITWAIT", w_wait);

    /* the longest framed line, and a buffer of exactly its length refused */
    n = p3_wire_loop_record(&r, rec, sizeof(rec));
    p3_base64url((const uint8_t *)rec, n, enc);
    k = p3_wire_line("REC", 0xFFFFFFFFu, token, enc, line, cap);
    plus = p3_wire_line("REC", 0xFFFFFFFFu, token, enc, buf, k);
    printf("LINECAP %lu %lu\n", (unsigned long)k, (unsigned long)plus);
    printf("MAXLINE %s", k ? line : "<0>\n");
    r.seq = 1;
    n = p3_wire_loop_record(&r, rec, sizeof(rec));
    p3_base64url((const uint8_t *)rec, n, enc);
    k = p3_wire_line("REC", 1u, token, enc, line, cap);
    printf("SEQ1LINE %s", k ? line : "<0>\n");
    return 0;
}
'''


def longest_literal() -> int:
    n = 0
    for f in ("b3_app.c", "p3_rectx.c", "p3_pull.c"):
        for m in re.finditer(r'"((?:[^"\\\n]|\\.)*)"', gen.strip_comments((FW / f).read_text())):
            n = max(n, len(m.group(1)))
    return n


def app_macro(name: str) -> int:
    m = re.search(rf"#define {name} (\d+)u", APP)
    assert m, name
    return int(m.group(1))


def frame_types() -> set:
    return set(re.findall(r'(?:build_payload_frame|send_payload|build_frame)\("([A-Z_]+)"', APP))


def sparse_entries() -> int:
    m = re.search(r"static char g_words_b64\[(\d+)\];", APP)
    assert m
    return int(m.group(1)) - 1


def driver() -> dict:
    """Build and run the generated driver once per process; parse its probes and its lines."""
    if "d" in _CACHE:
        return _CACHE["d"]
    cc = os.environ.get("CC", "cc")
    if shutil.which(cc) is None:
        raise AssertionError("no host C compiler: a failure, never a skip")
    BUILD.mkdir(parents=True, exist_ok=True)
    src = BUILD / "bounds_driver.c"
    src.write_text(DRIVER)
    exe = BUILD / "bounds_driver"
    units = [str(FW / u) for u in ("b3_record.c", "b3_carto.c", "b2_search.c", "b3_wire.c", "p3_derive.c")]
    p = subprocess.run([cc, "-std=c99", "-O1", "-w", "-I", str(FW), "-o", str(exe), str(src), *units], capture_output=True, text=True)
    if p.returncode != 0:
        raise AssertionError(f"the bound driver did not build:\n{p.stderr}")
    out = subprocess.run([str(exe), str(longest_literal()), str(sparse_entries()), str(app_macro("B3_LINE_MAX")), TOKEN],
                         capture_output=True, text=True, check=True).stdout
    probes, lines = {}, {}
    for ln in out.split("\n"):
        if not ln:
            continue
        tag, _, rest = ln.partition(" ")
        if tag in ("MAXLINE", "SEQ1LINE"):
            lines[tag] = rest + "\n"
        else:
            probes[tag] = [int(x) for x in rest.split()]
    _CACHE["d"] = {"probes": probes, "lines": lines}
    return _CACHE["d"]


class TheBounds(unittest.TestCase):
    def test_the_declared_bounds_are_the_derived_ones(self):
        d = driver()["probes"]
        block = max(d[t][0] for t in BLOCK_TYPES)
        payload = max(d[t][0] for t in PAYLOAD_TYPES)
        self.assertEqual(block, d["BLOCK_O_SEARCH"][0], "the O search block with its largest ledger is the largest block")
        self.assertEqual(payload, d["REC"][0], "the loop record with that block is the largest payload")
        enc = 4 * math.ceil(payload / 3)
        types = frame_types()
        self.assertEqual(types, set(PAYLOAD_TYPES), "every frame type the application builds is measured")
        line = len("P3L5 ") + max(len(t) for t in types) + 1 + 10 + 1 + 32 + 1 + enc + 1 + 8 + 1
        self.assertEqual(app_macro("B3_SEARCH_BLOCK_MAX"), block + 1)
        self.assertEqual(app_macro("B3_PAYLOAD_MAX"), payload + 1)
        self.assertEqual(app_macro("B3_ENCODED_MAX"), enc + 1)
        self.assertEqual(app_macro("B3_LINE_MAX"), line + 1)
        self.assertGreaterEqual(longest_literal(), 60, "the string bound is the application's longest literal")

    def test_every_encoder_refuses_a_buffer_exactly_its_length_and_renders_in_one_byte_more(self):
        for tag, vals in driver()["probes"].items():
            if tag == "LINECAP":
                continue
            n, exact, plus = vals
            with self.subTest(encoder=tag):
                self.assertGreater(n, 0)
                self.assertEqual(exact, 0, "a buffer exactly the length has no room for the NUL")
                self.assertEqual(plus, n)
        k, refused = driver()["probes"]["LINECAP"]
        self.assertGreater(k, 0, "the longest line fits B3_LINE_MAX")
        self.assertEqual(refused, 0)
        self.assertEqual(k + 1, app_macro("B3_LINE_MAX") - (len("AUDIT_READY") - len("REC")),
                         "the REC line is the bound less the longer frame type's extra bytes")

    def test_every_outbound_and_resend_buffer_is_sized_by_its_bound(self):
        want = {"g_payload": "B3_PAYLOAD_MAX", "g_encoded": "B3_ENCODED_MAX", "g_body": "B3_LINE_MAX", "g_rec_line": "B3_LINE_MAX",
                "g_rec_scratch": "B3_LINE_MAX", "g_tx_line": "B3_LINE_MAX", "g_ready_line": "B3_LINE_MAX",
                "g_search_json": "B3_SEARCH_BLOCK_MAX"}
        for name, macro in want.items():
            with self.subTest(buffer=name):
                self.assertRegex(APP, rf"static char {name}\[{macro}\];", "a static (BSS) buffer of the bound")
        for name in ("g_payload", "g_encoded", "g_body", "g_rec_line", "g_rec_scratch", "g_tx_line", "g_ready_line"):
            self.assertIsNone(re.search(rf"static char {name}\[\d+\]", APP), f"{name}: no hard-coded size")
        calls = re.findall(r"(p3_wire_(?:loop_record|identity|sign_request|summary|audit_ready|audit_sparse|closing|hb|audit_wait))\(", APP)
        self.assertEqual(len(calls), 9)
        self.assertEqual(APP.count("g_payload, sizeof(g_payload)"), 9, "every payload builder is given the payload buffer's own size")
        self.assertIn("b3_orch_record_block(&O, g_search_json, sizeof(g_search_json))", APP)


class TheFailClosedPaths(unittest.TestCase):
    def body(self, signature: str) -> str:
        start = APP.index(signature)
        return APP[start:APP.index("\n}\n", start)]

    def test_base64_is_checked_before_it_runs_and_an_encoder_s_zero_is_protocol(self):
        b = self.body("static size_t build_payload_frame(")
        check = b.index("4u * ((plain_len + 2u) / 3u) + 1u > sizeof(g_encoded)")
        self.assertLess(check, b.index("p3_base64url("), "the capacity check precedes the encoding")
        self.assertIn('p3_stop(P3_PROTOCOL, "PROTOCOL_FRAME: the encoded payload would not fit")', b)
        self.assertIn('p3_stop(P3_PROTOCOL, "PROTOCOL_FRAME: payload builder overflowed")', b)
        self.assertEqual(gen.strip_comments(APP).count("p3_base64url("), 1, "the only encoding is the checked one")
        f = self.body("static size_t build_frame(")
        self.assertIn('p3_stop(P3_PROTOCOL, "PROTOCOL_FRAME: outbound line too long")', f)

    def test_an_incomplete_observation_and_an_unrendered_block_are_protocol(self):
        b = self.body("static int run_candidate(")
        obs = b.index("if (b3_orch_observe(&O, S.seq, g_tables_u64) != 0)")
        self.assertIn('p3_stop(P3_PROTOCOL, "PROTOCOL_OBSERVE: the orchestrator could not complete the observation")', b[obs:obs + 300])
        blk = b.index("if (!is_baseline && rec.search == NULL)")
        self.assertIn('p3_stop(P3_PROTOCOL, "PROTOCOL_BLOCK: the search block did not render")', b[blk:blk + 200])
        self.assertLess(obs, blk)
        self.assertLess(blk, b.index('emit_record(&rec, "SCORED")'), "no SCORED record before its block is known")

    def test_the_identity_and_the_session_init_refuse_a_wrong_profile_before_any_candidate(self):
        ident = self.body("static int establish_identity(")
        self.assertIn("b3_profile(S.page.seed, S.page.budget, g_pairs_total) == B3_PROFILE_NONE", ident)
        self.assertIn("in.carto_version = B3_CARTO_VERSION;", ident)
        self.assertIn("in.arms = B3_WIRE_ARMS;", ident)
        self.assertIn("in.b1_map_cost = B3_WIRE_B1_MAP_COST;", ident)
        init = self.body("static void b3_session_init(")
        self.assertIn("b3_orch_init(&O, S.page.seed, S.page.budget, g_pairs_total, g_pair_first, g_pair_count,", init)
        self.assertIn('"STOP_PAGE: the identity page\'s session parameters were refused"', init)


def instrument():
    if "inst" not in _CACHE:
        inst.bind(inst.DEFAULT_ROOT, require_git=False)
        import l5_notary as n  # noqa: E402  (the instrument's host modules, bound read-only)
        import l6_reader as lrd  # noqa: E402
        _CACHE["inst"] = (n, lrd)
    return _CACHE["inst"]


class FakeSerial:
    """The serial handle L6LineReader reads: `in_waiting` and `read(n)`, fed in pieces."""

    def __init__(self):
        self.buf = b""

    def feed(self, b: bytes):
        self.buf += b

    @property
    def in_waiting(self):
        return len(self.buf)

    def read(self, n):
        out, self.buf = self.buf[:n], self.buf[n:]
        return out


class TheHostReadsTheLongestLine(unittest.TestCase):
    def test_the_longest_line_in_pieces_of_every_size_through_the_reader_and_the_parser(self):
        n, lrd = instrument()
        line = driver()["lines"]["MAXLINE"]
        self.assertTrue(line.startswith(f"P3L5 REC 4294967295 {TOKEN} "))
        self.assertEqual(len(line) + 1, app_macro("B3_LINE_MAX") - (len("AUDIT_READY") - len("REC")))
        raw = line.encode()
        for piece in (1, 7, 63, 64, 1000, 4096, len(raw)):
            with self.subTest(piece=piece):
                ser, clock = FakeSerial(), iter(range(10 ** 6))
                rd = lrd.L6LineReader(ser, clock_mono=lambda: next(clock), clock_wall=lambda: 0.0)
                got = []
                for i in range(0, len(raw), piece):
                    ser.feed(raw[i:i + piece])
                    got += [x[0] for x in rd.poll()]
                self.assertEqual(len(got), 1, "one line, however it arrived")
                self.assertEqual(got[0].rstrip("\n"), line.rstrip("\n"))
                self.assertEqual(rd.take_fragments(), [])
                f = n.parse_line(got[0])
                self.assertEqual((f["type"], f["seq"], f["token"]), ("REC", 4294967295, TOKEN))
                rec = n.decode_payload(f["payload"])
                self.assertEqual(rec["seq"], 4294967295)
                self.assertEqual(len(rec["search"]["ledger"]["behaviour_delta"]), 384)
                self.assertEqual(len(rec["search"]["ledger"]["decoded"]), 292)

    def test_the_collector_files_the_record_and_a_torn_first_transmission_is_quarantined(self):
        n, lrd = instrument()
        line = driver()["lines"]["SEQ1LINE"]
        raw = line.encode()
        ser, clock = FakeSerial(), iter(range(10 ** 6))
        rd = lrd.L6LineReader(ser, clock_mono=lambda: next(clock), clock_wall=lambda: 0.0)
        col = n.Collector(TOKEN, heartbeat_s=10, clock=lambda: 0.0)
        ser.feed(raw[:5000])                                   # the first transmission, torn: no line end
        self.assertEqual(rd.poll(), [])
        frag = rd.quarantine("timeout")                        # the host's wait ran out: the residue is quarantined
        self.assertIsNotNone(frag)
        self.assertEqual(frag["bytes"], 5000)
        ser.feed(raw)                                          # the resend: the SAME bytes
        got = [x[0] for x in rd.poll()]
        self.assertEqual(len(got), 1)
        for ln in got:
            col.on_line(ln, now=0.0)
        self.assertIsNone(col.epoch_end, col.epoch_end)
        self.assertEqual(len(col.loop_records), 1)
        self.assertEqual(col.loop_records[0]["seq"], 1)
        self.assertEqual(len(col.loop_records[0]["search"]["ledger"]["decoded"]), 292)

    def test_a_torn_line_followed_by_a_new_head_is_resynchronised(self):
        n, lrd = instrument()
        raw = driver()["lines"]["SEQ1LINE"].encode()
        ser, clock = FakeSerial(), iter(range(10 ** 6))
        rd = lrd.L6LineReader(ser, clock_mono=lambda: next(clock), clock_wall=lambda: 0.0)
        ser.feed(raw[:7000] + raw)                             # a torn copy glued to the full resend, no quarantine asked
        got = [x[0] for x in rd.poll()]
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0].rstrip("\n"), raw.decode().rstrip("\n"))
        frags = rd.take_fragments()
        self.assertEqual(len(frags), 1)
        self.assertTrue(frags[0]["reason"].startswith("resync"), frags[0]["reason"])
        self.assertEqual(frags[0]["bytes"], 7000)


class TheAxiAllowlist(unittest.TestCase):
    """The application's decode against rtl/b1/b1_axil.v (the B1 carrier B3 runs on), as tests/test_b1_carrier.py
    ports the instrument's check; mismatches only."""
    DEFINES = {m.group(1): int(m.group(2), 16) for m in re.finditer(r"#define (P3_\w+) (0x[0-9A-Fa-f]+)u", APP)}

    def _fn(self, name):
        start = APP.index(f"static int {name}(uint32_t off)")
        return APP[start:APP.index("\n}", start)]

    def app_offsets(self, fn):
        body = self._fn(fn)
        out = set()
        for m in re.finditer(r"off == (P3_\w+)", body):
            out.add(self.DEFINES[m.group(1)])
        for m in re.finditer(r"off >= (P3_\w+) && off < P3_\w+ \+ (\d+)u \* 4u", body):
            base, k = self.DEFINES[m.group(1)], int(m.group(2))
            out.update(base + 4 * i for i in range(k))
        return out

    def rtl_reads(self):
        out = set()
        for m in re.finditer(r"ra == 16'h([0-9A-Fa-f]{4})", RTL):
            out.add(int(m.group(1), 16))
        for m in re.finditer(r"ra >= 16'h([0-9A-Fa-f]{4}) && ra < 16'h([0-9A-Fa-f]{4})", RTL):
            out.update(range(int(m.group(1), 16), int(m.group(2), 16), 4))
        return out

    def rtl_writes(self):
        out = {0x2000}
        for m in re.finditer(r"wire wr_\w+\s*=\s*\(wa >= 16'h([0-9A-Fa-f]{4})\) && \(wa < 16'h([0-9A-Fa-f]{4})\)", RTL):
            out.update(range(int(m.group(1), 16), int(m.group(2), 16), 4))
        return out

    def test_reads_lie_inside_the_rtl_and_the_rtl_s_reads_are_all_the_application_s(self):
        app, rtl = self.app_offsets("axi_readable"), self.rtl_reads()
        self.assertTrue(app and rtl)
        self.assertEqual(sorted(hex(x) for x in app - rtl), [])
        self.assertEqual(sorted(hex(x) for x in rtl - app), [])
        self.assertNotIn(0x2000, app, "CTRL is write-only in the RTL: never read")
        self.assertIn(0x2034, app, "VARIANT is read at identity")

    def test_writes_lie_inside_the_rtl_and_only_the_key_window_is_left(self):
        app, rtl = self.app_offsets("axi_writable"), self.rtl_writes()
        self.assertEqual(sorted(hex(x) for x in app - rtl), [])
        self.assertEqual(rtl - app, KEY_WINDOW)

    def test_the_key_window_is_never_named(self):
        for off in KEY_WINDOW:
            self.assertNotIn(f"0x{off:04X}u", APP)
            self.assertNotIn(f"0x{off:04x}u", APP)


if __name__ == "__main__":
    unittest.main()
