"""b3/host/b3_session.py — the host-only reference orchestrator (lifecycle 2, the session unit).

Held here: the opening and closing blank baselines and the record formula 2 + N × (3 × B + 3); the
six arm orders (RFO, FOR, ORF, ROF, OFR, FRO) and a later slice that keeps the absolute pair index,
that pair's seeds and that pair's arm order (its blocks byte-identical to the full experiment's); B3
and B3Q (the latter through the production plan / prediction builders — 1 pair at budget 40: 120
search + 3 holdout candidates, 40 ledger entries, 125 records with the baselines — accepted by
`b3_records.context_from`, which is what the B3Q plan's `b1_map_cost` was added for); every O-arm
block field for field against the prediction (the ledger entry, the final commitment on the last
search record and on the holdout record) and every arm's best and holdout, the fitness-sequence
digest included; the early stop at every kind of position (the opening baseline, a search, each of
the three holdouts, the closing baseline) — nothing proposed after it and no closing baseline;
illegal inputs (slice, seed count, seed shape, budget, wrong types, any fitness but the preregistered F1 — even a self-consistent F2 context, refused before any arm runs) refused by name; the full
experiment and a later slice accepted by `b3_records.validate_run_log` with no finding; and — after
`run_online` learned to emit record blocks — the committed eight-pair prediction regenerated byte for
byte and reproduced by the session record for record.

The committed-prediction test reads `evidence/b3/plan.json` / `prediction.json` (the canonical
preflight of 7cb0879, pre-S0: no B3 manifest exists yet; the stage-aware coverage of preregistration
§9 arrives with the manifest unit). It is a regression guard on the reference, not a stage assertion.
"""
from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

R = Path(__file__).resolve().parents[2]
for p in (R / "host", R / "b3/host", R / "b3/tests"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))
import b1_model as bm  # noqa: E402
import b2_landscape as bl  # noqa: E402
import b2_maps as bmaps  # noqa: E402
import b2_search as bs  # noqa: E402
import b3_carto as carto_mod  # noqa: E402
import b3_gate as b3g  # noqa: E402
import b3_online_arm as oa  # noqa: E402
import b3_plan as pl  # noqa: E402
import b3_records as brec  # noqa: E402
import b3_session as bsess  # noqa: E402
import b3_test_fixtures as fx  # noqa: E402

TRUTH = bm.truth_mapping()
MASKS = bl.universe_mask(TRUTH)
FAB = bs.ModelFabric(TRUTH)
SELF_MAP = bmaps.load_self_map()
VIEW = bmaps.MapView(SELF_MAP, bl.train_vectors())
MAP_SHA = bmaps.sha256_of(SELF_MAP)
BUDGET = 4
SEEDS6 = [(1000 + i, 5000 + i) for i in range(6)]
WIRE = bsess.ARM_WIRE


def make_plan(budget, pairs, session="B3") -> dict:
    return {"schema": "b3_plan", "schema_version": pl.SCHEMA_VERSION, "lifecycle": pl.LIFECYCLE, "session": session,
            "fitness": "F1", "budget_per_arm": budget, "pairs": pairs, "seed_derivation": {"master_seed": 716169644},
            "map": {"sha256": MAP_SHA}, "carto_version": carto_mod.CARTO_VERSION, "b1_map_cost": oa.B1_MAP_COST}


def run6(first=0, count=6, **kw) -> bsess.Session:
    return bsess.run(BUDGET, 6, first, count, SEEDS6, FAB, VIEW, TRUTH, MASKS, **kw)


def searches(s, pair):
    return [c for c in s.candidates if not c.is_baseline and c.pair == pair and not c.holdout]


def holdouts(s, pair):
    return [c for c in s.candidates if not c.is_baseline and c.pair == pair and c.holdout]


def fitness_sequence(s) -> list[int]:
    out = []
    for c in s.candidates:
        if c.is_baseline:
            continue
        b = json.loads(c.block)
        out.append(b["holdout"] if c.holdout else b["fitness"])
    return out


class Order(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.s = run6()

    def test_the_baselines_and_the_record_formula(self):
        s = self.s
        self.assertEqual(len(s.candidates), bsess.records(6, BUDGET))
        self.assertEqual(bsess.records(6, BUDGET), 2 + 6 * (3 * BUDGET + 3))
        self.assertEqual(bsess.records(8, 1000), 24026)
        self.assertEqual(bsess.records(8, 1000, sessions=2), 24028)
        self.assertEqual(s.records, len(s.candidates))
        first, last = s.candidates[0], s.candidates[-1]
        for c in (first, last):
            self.assertTrue(c.is_baseline)
            self.assertEqual((c.pair, c.arm, c.holdout, c.genome, c.block), (-1, None, False, 0, ""))
        self.assertEqual([c.seq for c in s.candidates], list(range(1, len(s.candidates) + 1)))
        self.assertFalse(s.ended_early)
        self.assertEqual(sum(1 for c in s.candidates if c.is_baseline), 2)

    def test_the_six_arm_orders(self):
        s = self.s
        for r, letters in enumerate(pl.ARM_SEQUENCE):
            with self.subTest(pair=r, order=letters):
                self.assertEqual("".join(bsess.arm_order(r)), letters)
                se, ho = searches(s, r), holdouts(s, r)
                self.assertEqual([c.arm for c in se], [WIRE[a] for a in letters for _ in range(BUDGET)])
                self.assertEqual([c.arm for c in ho], [WIRE[a] for a in letters])
                for c in se + ho:
                    b = json.loads(c.block)
                    self.assertEqual((b["pair"], b["landscape_seed"], b["operator_seed"]), (r, *SEEDS6[r]))
                    self.assertEqual(b["arm"], brec.ARM_LETTER[c.arm])
                    self.assertEqual(b["holdout"] is not None, c.holdout)
                    self.assertEqual(("ledger" in b), c.arm == "online" and not c.holdout)
                self.assertEqual([json.loads(c.block)["eval"] for c in se], [n for _ in letters for n in range(1, BUDGET + 1)])

    def test_a_later_slice_keeps_the_absolute_pair_its_seeds_and_its_order(self):
        s = run6(4, 2)
        self.assertEqual(len(s.candidates), bsess.records(2, BUDGET))
        self.assertEqual(sorted({c.pair for c in s.candidates if not c.is_baseline}), [4, 5])
        self.assertEqual([c.arm for c in holdouts(s, 4)], [WIRE[a] for a in "OFR"])
        self.assertEqual([c.arm for c in holdouts(s, 5)], [WIRE[a] for a in "FRO"])
        full = self.s
        for r in (4, 5):
            self.assertEqual([c.block for c in searches(s, r) + holdouts(s, r)], [c.block for c in searches(full, r) + holdouts(full, r)],
                             "a later slice must produce byte-identical blocks for its pairs")
            self.assertEqual([c.genome for c in searches(s, r)], [c.genome for c in searches(full, r)])
        self.assertEqual(s.candidates[1].pair, 4)
        self.assertEqual(json.loads(s.candidates[1].block)["landscape_seed"], SEEDS6[4][0])

    def test_the_candidate_genome_is_the_scored_child(self):
        s = self.s
        for c in searches(s, 0)[:BUDGET]:                      # arm R of pair 0: its moves from the reference
            self.assertNotEqual(c.genome, 0)
        land = bl.Landscape("F1", SEEDS6[0][0], masks=MASKS, truth=TRUTH)
        res = bs.run(bs.ARM_RANDOM_SAFE, land, None, SEEDS6[0][1], BUDGET, FAB, log_moves=True, pair=0)
        self.assertEqual([c.genome for c in searches(s, 0)[:BUDGET]], [m["genome"] for m in res.moves])
        self.assertEqual(holdouts(s, 0)[0].genome, res.champion.genome)
        self.assertEqual([c.block for c in searches(s, 0)[:BUDGET]], res.blocks)
        resf = bs.run(bs.ARM_MAP_GUIDED, land, VIEW, SEEDS6[0][1], BUDGET, FAB, log_moves=True, pair=0)
        self.assertEqual([c.genome for c in searches(s, 0)[BUDGET:2 * BUDGET]], [m["genome"] for m in resf.moves])
        self.assertEqual(holdouts(s, 0)[1].genome, resf.champion.genome)
        oo = oa.run_online(land, SEEDS6[0][1], BUDGET, FAB, pair=0)
        self.assertEqual([c.genome for c in searches(s, 0)[2 * BUDGET:]], oo.genomes)
        self.assertEqual(holdouts(s, 0)[2].genome, oo.champion.genome)
        self.assertEqual([c.block for c in searches(s, 0)[2 * BUDGET:]], oo.blocks)
        # every scored child is its parent's genome with the move's bits flipped — never the blank genome, never a copy of another arm's
        for c in searches(s, 0):
            b = json.loads(c.block)
            self.assertEqual(bin(c.genome).count("1") <= 4 * b["eval"], True)
            self.assertNotEqual(c.genome, 0)

    def test_a_non_record_capable_o_run_is_refused(self):
        """The session never accepts an online result that produced no blocks (a gate control passed
        off as an O run): a named RuntimeError, nothing proposed for that pair."""
        from unittest import mock
        real = oa.run_online

        def control(land, oseed, budget, fabric, keep_ledger=True, pair=0, **kw):
            return real(land, oseed, budget, fabric, keep_ledger=False, pair=pair)
        with mock.patch.object(oa, "run_online", control):
            with self.assertRaises(RuntimeError) as cm:
                run6(0, 1)
        self.assertIn("not a record-capable O run", str(cm.exception))


class AgainstThePrediction(unittest.TestCase):
    """Every value the session produces equals the prediction over the same seeds — produced by the
    arms' own runs, never copied (run takes no prediction)."""

    @classmethod
    def setUpClass(cls):
        cls.seeds = SEEDS6[:3]
        cls.pred = pl.build_prediction("F1", BUDGET, cls.seeds)
        cls.s = bsess.run(BUDGET, 3, 0, 3, cls.seeds, FAB, VIEW, TRUTH, MASKS)

    def test_run_takes_no_prediction(self):
        import inspect
        self.assertNotIn("prediction", inspect.signature(bsess.run).parameters)

    def test_every_o_block_field_for_field(self):
        for r in range(3):
            o = self.pred["pairs"][r]["runs"]["O"]
            se = [c for c in searches(self.s, r) if c.arm == "online"]
            ho = [c for c in holdouts(self.s, r) if c.arm == "online"]
            self.assertEqual(len(se), BUDGET)
            for n, c in enumerate(se):
                b = json.loads(c.block)
                self.assertEqual(b3g.deep_findings(o["ledger"][n], b["ledger"], f"pair {r} entry {n}"), [])
                self.assertEqual(b["fitness"], o["ledger"][n]["fitness"])
                self.assertEqual(b["move"], {"bits": o["ledger"][n]["intervention"], "kind": o["ledger"][n]["move_kind"]})
            self.assertEqual(json.loads(se[-1].block)["state_sha256"], o["final_state_sha256"])
            self.assertEqual(json.loads(se[-1].block)["best"], o["best_train"])
            hb = json.loads(ho[0].block)
            self.assertEqual((hb["state_sha256"], hb["holdout"], hb["move"], hb["fitness"], hb["parent_born"], hb["selected"], hb["eval"]),
                             (o["final_state_sha256"], o["champion_holdout"], None, None, None, False, BUDGET))
            self.assertNotIn("ledger", hb)
            self.assertEqual(json.loads(se[-1].block)["column_moves"], o["column_moves"])

    def test_every_arm_best_and_holdout_and_the_fitness_sequence_digest(self):
        for r in range(3):
            for a in "RFO":
                run = self.pred["pairs"][r]["runs"][a]
                se = [c for c in searches(self.s, r) if c.arm == WIRE[a]]
                ho = [c for c in holdouts(self.s, r) if c.arm == WIRE[a]]
                self.assertEqual(json.loads(se[-1].block)["best"], run["best_train"], (r, a))
                self.assertEqual(json.loads(ho[0].block)["holdout"], run["champion_holdout"], (r, a))
            self.assertEqual(json.loads(searches(self.s, r)[0].block)["best"] >= self.pred["pairs"][r]["base_train_fitness"], True)
        seq = fitness_sequence(self.s)
        self.assertEqual(len(seq), self.pred["fitness_sequence_length"])
        self.assertEqual(pl.sha256_json(seq), self.pred["fitness_sequence_sha256"])


class EarlyStop(unittest.TestCase):
    def _stop_at(self, seq):
        s = run6(0, 2, unscored_at=seq)
        self.assertTrue(s.ended_early)
        self.assertEqual(len(s.candidates), seq, "nothing may be proposed after the candidate that was not SCORED")
        self.assertEqual(s.candidates[-1].seq, seq)
        return s

    def test_the_opening_baseline(self):
        s = self._stop_at(1)
        self.assertTrue(s.candidates[0].is_baseline)

    def test_a_search_candidate(self):
        s = self._stop_at(3)
        self.assertFalse(s.candidates[-1].holdout)
        self.assertFalse(any(c.is_baseline for c in s.candidates[1:]))

    def test_each_of_the_three_holdouts(self):
        base = 1 + 3 * BUDGET
        for k in (1, 2, 3):
            with self.subTest(holdout=k):
                s = self._stop_at(base + k)
                self.assertTrue(s.candidates[-1].holdout)
                self.assertEqual(s.candidates[-1].arm, WIRE["RFO"[k - 1]])
                self.assertFalse(any(c.is_baseline for c in s.candidates[1:]))

    def test_a_search_of_the_second_pair(self):
        s = self._stop_at(1 + 3 * BUDGET + 3 + 2)
        self.assertEqual((s.candidates[-1].pair, s.candidates[-1].arm), (1, WIRE["F"]))

    def test_the_closing_baseline(self):
        total = bsess.records(2, BUDGET)
        s = self._stop_at(total)
        self.assertTrue(s.candidates[-1].is_baseline)

    def test_no_stop_runs_to_the_closing_baseline(self):
        s = run6(0, 2, unscored_at=None)
        self.assertFalse(s.ended_early)
        self.assertEqual(len(s.candidates), bsess.records(2, BUDGET))
        s2 = run6(0, 2, unscored_at=bsess.records(2, BUDGET) + 1)
        self.assertFalse(s2.ended_early)
        self.assertEqual([c.block for c in s2.candidates], [c.block for c in s.candidates])


class Refusals(unittest.TestCase):
    def _refuses(self, needle, *args, **kw):
        with self.assertRaises(ValueError) as cm:
            bsess.run(*args, **kw)
        self.assertIn(needle, str(cm.exception))

    def test_budget(self):
        for bad in (0, -1, True, "4", 4.0, None):
            with self.subTest(budget=bad):
                self._refuses("is not a positive integer", bad, 6, 0, 6, SEEDS6, FAB, VIEW, TRUTH, MASKS)

    def test_pairs_total_and_slice(self):
        self._refuses("pairs_total 0 is not an integer in 1..16", BUDGET, 0, 0, 1, [], FAB, VIEW, TRUTH, MASKS)
        self._refuses("pairs_total 17", BUDGET, 17, 0, 1, [(1, 1)] * 17, FAB, VIEW, TRUTH, MASKS)
        for first, count in ((6, 1), (0, 0), (-1, 1), (5, 2), (True, 1), (0, "6")):
            with self.subTest(slice=(first, count)):
                self._refuses(f"the session's pair slice ({first!r}, {count!r}) is not inside the experiment's 6 pairs",
                              BUDGET, 6, first, count, SEEDS6, FAB, VIEW, TRUTH, MASKS)

    def test_seeds(self):
        self._refuses("5 pair seeds for 6 pairs", BUDGET, 6, 0, 6, SEEDS6[:5], FAB, VIEW, TRUTH, MASKS)
        self._refuses("pair_seeds is not a list", BUDGET, 6, 0, 6, 716169644, FAB, VIEW, TRUTH, MASKS)
        for bad in ((1,), ("1000", 5000), (1000, True), (1000, 2 ** 32), (-1, 5000), 5):
            with self.subTest(seed=bad):
                self._refuses("pair 2's seeds", BUDGET, 6, 0, 6, SEEDS6[:2] + [bad] + SEEDS6[3:], FAB, VIEW, TRUTH, MASKS)

    def test_unscored_at_and_fitness(self):
        self._refuses("unscored_at 0 is not a positive integer seq", BUDGET, 6, 0, 1, SEEDS6, FAB, VIEW, TRUTH, MASKS, unscored_at=0)
        self._refuses("unscored_at '3'", BUDGET, 6, 0, 1, SEEDS6, FAB, VIEW, TRUTH, MASKS, unscored_at="3")
        for bad in (1, None, "F2", "garbage", "f1", "F1 "):
            with self.subTest(fitness=bad):
                self._refuses(f"fitness {bad!r} is not the preregistered 'F1'", BUDGET, 6, 0, 1, SEEDS6, FAB, VIEW, TRUTH, MASKS, fitness=bad)

    def test_a_self_consistent_f2_context_is_refused_before_any_arm_runs(self):
        """The owner's P2 on 10733ac: an internally consistent F2 plan / prediction passes context_from
        and validate_run_log — only the session may refuse it, and it must do so by name before
        bs.run or run_online is called (a type-only check would run the whole F2 session)."""
        from unittest import mock
        pred = pl.build_prediction("F2", BUDGET, SEEDS6[:3])
        plan = dict(make_plan(BUDGET, 3), fitness="F2")
        ctx = brec.context_from(plan, pred, 0, 3)                   # accepted: the validator binds a fitness, it does not choose one
        self.assertEqual(ctx.fitness, "F2")
        with mock.patch.object(bs, "run", side_effect=AssertionError("an arm ran")) as r, \
                mock.patch.object(oa, "run_online", side_effect=AssertionError("an arm ran")) as o:
            with self.assertRaises(ValueError) as cm:
                bsess.run_context(ctx, FAB, VIEW, TRUTH, MASKS)
            self.assertEqual(r.call_count + o.call_count, 0, "the refusal must precede every arm")
        self.assertEqual(str(cm.exception), "fitness 'F2' is not the preregistered 'F1'")
        with mock.patch.object(bs, "run", side_effect=AssertionError("an arm ran")), \
                mock.patch.object(oa, "run_online", side_effect=AssertionError("an arm ran")):
            with self.assertRaises(ValueError) as cm2:
                bsess.run(BUDGET, 3, 0, 3, SEEDS6[:3], FAB, VIEW, TRUTH, MASKS, fitness="garbage")
        self.assertEqual(str(cm2.exception), "fitness 'garbage' is not the preregistered 'F1'")

    def test_nothing_is_proposed_on_a_refusal(self):
        with self.assertRaises(ValueError):
            bsess.run(BUDGET, 6, 6, 1, SEEDS6, FAB, VIEW, TRUTH, MASKS)


class RecordsIntegration(unittest.TestCase):
    """The reference session, as loop_record 1.4.0 documents, passes the B3 record validator with no
    finding — the full experiment and a later slice."""

    @classmethod
    def setUpClass(cls):
        cls.pred = pl.build_prediction("F1", BUDGET, SEEDS6[:3])
        cls.plan = make_plan(BUDGET, 3)

    def test_the_full_experiment(self):
        ctx = brec.context_from(self.plan, self.pred, 0, 3)
        s = bsess.run_context(ctx, FAB, VIEW, TRUTH, MASKS)
        self.assertEqual(len(s.candidates), ctx.records)
        self.assertEqual(brec.validate_run_log(fx.run_log(ctx, s), ctx, common=False), [])

    def test_a_later_slice(self):
        ctx = brec.context_from(self.plan, self.pred, 1, 2)
        s = bsess.run_context(ctx, FAB, VIEW, TRUTH, MASKS)
        self.assertEqual(len(s.candidates), ctx.records)
        self.assertEqual(brec.validate_run_log(fx.run_log(ctx, s), ctx, common=False), [])
        wrong = brec.context_from(self.plan, self.pred, 0, 2)
        self.assertNotEqual(brec.validate_run_log(fx.run_log(wrong, s), wrong, common=False), [])


class Qualification(unittest.TestCase):
    """B3Q through the PRODUCTION builders (a lifecycle-2 gate fixture for the seeds): the plan and the
    prediction pass `b3_records.context_from` — the plan's `b1_map_cost` was missing (the owner's
    integration finding) — and the session gives 1 pair at budget 40: 120 search + 3 holdout
    candidates, 40 ledger entries, 125 records with the two baselines, accepted with no finding."""

    @classmethod
    def setUpClass(cls):
        cls.saved = b3g.THRESHOLDS["H2_bootstrap_experiments"]
        b3g.THRESHOLDS["H2_bootstrap_experiments"] = 100
        cls.tmp = Path(tempfile.mkdtemp())
        gate = fx.write_gate_fixture(cls.tmp / "gate_2")
        g = pl.gate_inputs(gate)
        _m, seeds, _s, _e = pl.session_seeds(g["pairs"], gate)
        cls.qplan = pl.build_qualification_plan("F1", MAP_SHA, seeds, gate)
        cls.qpred = pl.build_qualification_prediction("F1", MAP_SHA, seeds, gate)

    @classmethod
    def tearDownClass(cls):
        b3g.THRESHOLDS["H2_bootstrap_experiments"] = cls.saved
        shutil.rmtree(cls.tmp, True)

    def test_the_production_b3q_plan_and_prediction_bind_a_context(self):
        self.assertEqual(self.qplan["b1_map_cost"], 333)
        ctx = brec.context_from(self.qplan, self.qpred, 0, 1)
        self.assertEqual((ctx.budget, ctx.pairs_total, ctx.pair_count), (40, 1, 1))
        self.assertEqual(ctx.seeds, [tuple(x) for x in self.qplan["seed_derivation"]["pairs"]])

    def test_the_b3q_session(self):
        ctx = brec.context_from(self.qplan, self.qpred, 0, 1)
        s = bsess.run_context(ctx, FAB, VIEW, TRUTH, MASKS)
        se, ho = searches(s, 0), holdouts(s, 0)
        self.assertEqual((len(se), len(ho), len(s.candidates)), (120, 3, 125))
        self.assertEqual(sum(1 for c in se if "ledger" in json.loads(c.block)), 40)
        self.assertEqual(self.qplan["records"]["total"], s.records)
        self.assertEqual(brec.validate_run_log(fx.run_log(ctx, s), ctx, common=False), [])
        self.assertEqual(len(fitness_sequence(s)), 123)
        self.assertEqual(pl.sha256_json(fitness_sequence(s)), self.qpred["fitness_sequence_sha256"])


class CommittedPrediction(unittest.TestCase):
    """After `run_online` learned to emit record blocks, the committed eight-pair prediction (7cb0879)
    regenerates byte for byte, and the session reproduces it record for record."""

    @classmethod
    def setUpClass(cls):
        cls.plan = json.loads((R / "evidence/b3/plan.json").read_text())
        cls.pred_bytes = (R / "evidence/b3/prediction.json").read_bytes()
        cls.pred = json.loads(cls.pred_bytes)
        cls.ctx = brec.context_from(cls.plan, cls.pred, 0, cls.plan["pairs"])
        cls.s = bsess.run_context(cls.ctx, FAB, VIEW, TRUTH, MASKS)

    def test_the_prediction_regenerates_byte_for_byte(self):
        again = pl.build_prediction(self.plan["fitness"], self.plan["budget_per_arm"], self.ctx.seeds, self.plan["map"]["sha256"])
        self.assertEqual(json.dumps(again, indent=1, sort_keys=True) + "\n", self.pred_bytes.decode())

    def test_the_session_reproduces_it_record_for_record(self):
        ctx, s, pred = self.ctx, self.s, self.pred
        self.assertEqual(len(s.candidates), ctx.records)
        self.assertEqual(brec.validate_run_log(fx.run_log(ctx, s), ctx, common=False), [])
        for r in range(ctx.pairs_total):
            for a in "RFO":
                run = pred["pairs"][r]["runs"][a]
                se = [c for c in searches(s, r) if c.arm == WIRE[a]]
                ho = [c for c in holdouts(s, r) if c.arm == WIRE[a]]
                self.assertEqual(json.loads(se[-1].block)["best"], run["best_train"], (r, a))
                self.assertEqual(json.loads(ho[0].block)["holdout"], run["champion_holdout"], (r, a))
                if a == "O":
                    self.assertEqual([json.loads(c.block)["ledger"] for c in se], run["ledger"])
                    self.assertEqual(json.loads(se[-1].block)["state_sha256"], run["final_state_sha256"])
                    self.assertEqual(json.loads(ho[0].block)["state_sha256"], run["final_state_sha256"])
        seq = fitness_sequence(s)
        self.assertEqual(len(seq), pred["fitness_sequence_length"])
        self.assertEqual(pl.sha256_json(seq), pred["fitness_sequence_sha256"])
        self.assertEqual([json.loads(searches(s, r)[-1].block)["pair"] for r in range(8)], list(range(8)))


if __name__ == "__main__":
    unittest.main()
