#!/usr/bin/env python3
"""ARM-gate fixture for tb/b1/tb_b1_core.v, produced by the SAME signer library the host uses
(the instrument's validators.signer, bound read-only) — under the B1 contract: every payload's
twelve table words are ZERO (the host attests no semantics), the fabric's INITs are arbitrary
and known only to the bench, and the bench checks that the readout equals the fabric.

Emits tb/b1/b1_fixture.vh with KEY_A/KEY_B, NONCE_SEED, six bench INITs, nonces n0..n2, the
payload+tag words per case, and the expected readout words. Cases:
  VALID1, VALID2   correctly signed, zero tables — must ARM and expose the fabric's tables
  UNSIGNED         tag zero            — F_ARM_AUTH
  WRONG_COMMIT     tag for another commit — F_ARM_AUTH
  ATTESTED         correctly signed but with NON-zero tables (the host attested semantics):
                   the gate is indifferent by design; the bench records that tables_match
                   is only an observation. The HOST validator (host/b1_records.py) refuses
                   such a reply; the fabric does not — the contract is enforced where the
                   semantics originate.
"""
import hashlib
import os
import sys
import tempfile
from pathlib import Path

R = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(R / "host"))
import claimb_r1p_instrument as inst  # noqa: E402

inst.bind(inst.DEFAULT_ROOT, require_git=False)
from validators import nonce as nn, signer as sg  # noqa: E402

KEY = bytes(range(16))
KEY_B = bytes(range(16, 32))
SEED = 0x9E3779B97F4A7C15
ZERO = [0] * 6
# the bench's fabric: six arbitrary tables (not the targets, not all-zero): the readout must
# equal THESE, which nothing in any payload names
INITS = [0x0123456789ABCDEF, 0xFEDCBA9876543210, 0x00000000F0F0F0F0, 0x8000000000000001, 0x0000000000000030, 0x5555AAAA5555AAAA]
n = nn.sequence(SEED, 3)
tmp = Path(tempfile.mkdtemp()); kp = tmp / "K"; kp.write_bytes(KEY); os.chmod(kp, 0o400)
holder = sg.KeyHolder(kp)


def commit(label): return hashlib.sha256(label.encode()).digest()
def verdict(c): return {"writable": True, "candidate_sha256": c.hex()}


c1, c2, c3, c4 = commit("b1-cand1"), commit("b1-cand2"), commit("b1-cand3"), commit("b1-cand4")
cases = {}
cases["VALID1"] = sg.sign_arm(holder, verdict(c1), c1, ZERO, n[0].to_bytes(8, "little")).words()
cases["VALID2"] = sg.sign_arm(holder, verdict(c2), c2, ZERO, n[1].to_bytes(8, "little")).words()
p = sg.sign_arm(holder, verdict(c1), c1, ZERO, n[0].to_bytes(8, "little"))
cases["UNSIGNED"] = sg.ArmPayload(p.candidate_commit, p.expected_tables, p.nonce, bytes(16)).words()
q = sg.sign_arm(holder, verdict(c3), c3, ZERO, n[0].to_bytes(8, "little"))
cases["WRONG_COMMIT"] = sg.ArmPayload(c4, q.expected_tables, q.nonce, q.tag).words()
cases["ATTESTED"] = sg.sign_arm(holder, verdict(c1), c1, INITS, n[0].to_bytes(8, "little")).words()

out = ["// generated by tb/b1/gen_b1_fixture.py — do not edit",
       f"localparam [127:0] KEY_A = 128'h{int.from_bytes(KEY, 'little'):032x};",
       f"localparam [127:0] KEY_B = 128'h{int.from_bytes(KEY_B, 'little'):032x};",
       f"localparam [63:0] SEED = 64'h{SEED:016x};"]
out += [f"localparam [63:0] N{i} = 64'h{v:016x};" for i, v in enumerate(n)]
out += [f"localparam [63:0] INIT{i} = 64'h{v:016x};" for i, v in enumerate(INITS)]
for name, w in cases.items():
    assert len(w) == 24
    out.append(f"localparam [767:0] {name} = 768'h" + "".join(f"{x:08x}" for x in w) + ";")
out.append(f"localparam [255:0] C1 = 256'h{c1.hex()}; localparam [255:0] C2 = 256'h{c2.hex()};")
(R / "tb/b1/b1_fixture.vh").write_text("\n".join(out) + "\n")
print("fixture:", list(cases), "nonces", [hex(x) for x in n])
