#!/usr/bin/env bash
# Build the B1 standalone image (b1_app.elf/.bin) with the instrument's pinned xPack
# toolchain (read-only use of zynq-psoracle's toolchain directory) and the same
# hand-assembled Cortex-A9 standalone BSP from Xilinx 2025.2 embeddedsw sources that the
# P3 images were built with (zynq-psoracle/firmware/bsp/build.sh, copied and re-pointed).
# Host-only: produces an ELF and a raw binary; touches no board.
#
#   IMAGE=b1_app bash firmware/b1/bsp/build.sh
#
# The B1 image links b1_app.c, b1_carto.c and b1_wire.c in place of the instrument's
# p3_app.c, p3_search.c and p3_wire.c; p3_derive.c, p3_rectx.c and p3_pull.c are the
# instrument's own files byte for byte (firmware/b1/IMPORT.json). The data header
# firmware/b1/p3_data.h is generated by host/gen_b1_data.py WITHOUT the operator tables.
set -euo pipefail

REPO=/home/test/zynq_fabricmap
INSTRUMENT=${PSORACLE_ROOT:-/home/test/zynq_psoracle}
TC=$INSTRUMENT/toolchain/xpack-arm-none-eabi-gcc-14.2.1-1.1
CC=$TC/bin/arm-none-eabi-gcc
SA=/home/test/Xilinx/2025.2/data/embeddedsw/lib/bsp/standalone_v9_4/src
WD=/home/test/Xilinx/2025.2/data/embeddedsw/XilinxProcessorIPLib/drivers/scuwdt_v2_6/src
FW=$REPO/firmware/b1
BSP=$FW/bsp
OUT=$BSP/out
IMAGE=${IMAGE:-b1_app}
mkdir -p "$OUT"

ARCH="-mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard"
INC="-I$BSP/include -I$SA/common -I$SA/arm/common -I$SA/arm/common/gcc \
     -I$SA/arm/cortexa9 -I$SA/arm/cortexa9/gcc -I$WD"
BSP_CFLAGS="$ARCH -std=gnu11 -O2 -g $INC -DUSE_AMP=0 -ffunction-sections -fdata-sections"
APP_CFLAGS="$ARCH -std=c99 -O2 -g $INC -Wall -Wextra -ffreestanding -ffunction-sections -fdata-sections"

ASM_SRCS="arm/cortexa9/gcc/boot.S arm/cortexa9/gcc/cpu_init.S \
          arm/cortexa9/gcc/translation_table.S arm/cortexa9/gcc/xil-crt0.S \
          arm/cortexa9/gcc/asm_vectors.S"
C_SRCS="arm/cortexa9/xil_cache.c arm/cortexa9/xil_mmu.c arm/cortexa9/xil_misc_psreset_api.c \
        arm/cortexa9/xl2cc_counter.c arm/cortexa9/xtime_l.c \
        arm/common/vectors.c arm/common/xil_exception.c \
        common/xil_assert.c common/xil_printf.c common/print.c common/xil_mem.c \
        common/xil_sutil.c common/xil_util.c common/outbyte.c common/inbyte.c"
SYS_SRCS="arm/common/gcc/sbrk.c arm/common/gcc/_sbrk.c arm/common/gcc/write.c \
          arm/common/gcc/read.c arm/common/gcc/close.c arm/common/gcc/fstat.c \
          arm/common/gcc/isatty.c arm/common/gcc/lseek.c arm/common/gcc/_exit.c \
          arm/common/gcc/_open.c arm/common/gcc/open.c arm/common/gcc/unlink.c \
          arm/common/gcc/getpid.c arm/common/gcc/kill.c arm/common/gcc/errno.c \
          arm/common/gcc/abort.c"
WDT_SRCS="xscuwdt.c xscuwdt_g.c xscuwdt_sinit.c"

OBJS=()
for s in $ASM_SRCS; do o="$OUT/$(echo "$s" | tr / _).o"; "$CC" $BSP_CFLAGS -c "$SA/$s" -o "$o"; OBJS+=("$o"); done
for s in $C_SRCS $SYS_SRCS; do o="$OUT/$(echo "$s" | tr / _).o"; "$CC" $BSP_CFLAGS -c "$SA/$s" -o "$o"; OBJS+=("$o"); done
for s in $WDT_SRCS; do o="$OUT/wd_$s.o"; "$CC" $BSP_CFLAGS -c "$WD/$s" -o "$o"; OBJS+=("$o"); done

"$CC" $BSP_CFLAGS -c "$BSP/src/console.c" -o "$OUT/console.o"; OBJS+=("$OUT/console.o")
for s in b1_app.c p3_derive.c b1_carto.c b1_wire.c p3_rectx.c p3_pull.c; do
  "$CC" $APP_CFLAGS -c "$FW/$s" -o "$OUT/$s.o"; OBJS+=("$OUT/$s.o")
done

CRTI=$("$CC" $ARCH -print-file-name=crti.o)
CRTBEGIN=$("$CC" $ARCH -print-file-name=crtbegin.o)
CRTEND=$("$CC" $ARCH -print-file-name=crtend.o)
CRTN=$("$CC" $ARCH -print-file-name=crtn.o)
"$CC" $ARCH -nostartfiles -Wl,--gc-sections -Wl,--build-id=none \
      -Wl,-T,"$BSP/lscript.ld" -Wl,-Map,"$OUT/$IMAGE.map" \
      -o "$OUT/$IMAGE.elf" "$CRTI" "$CRTBEGIN" "${OBJS[@]}" \
      -Wl,--start-group -lgcc -lc -lm -Wl,--end-group "$CRTEND" "$CRTN"
echo "LINK OK -> $OUT/$IMAGE.elf"
"$TC/bin/arm-none-eabi-size" "$OUT/$IMAGE.elf"
"$TC/bin/arm-none-eabi-objcopy" -O binary "$OUT/$IMAGE.elf" "$OUT/$IMAGE.bin"
echo "IMAGE  -> $OUT/$IMAGE.bin"
sha256sum "$OUT/$IMAGE.bin"
