#!/usr/bin/env python3
"""Generate the carrier's frozen constants from the committed spec and report.

The scorer's 64 vectors and 6 target truth tables are not typed into Verilog. They are
emitted here from `specs/reachability_spec_v1.json` and the production
`reachability_report.json`, both hash-pinned in the header this writes, so the RTL's
constants have exactly one source and a transcription error is not expressible.

The same reason `local_map` is generated rather than written, and `phenotype_manifest`
pins whole frames rather than a summary: anything a human retypes is a place where the
artifact and the authority can quietly disagree.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

TOOL_VERSION = "gen_carrier_constants.py/1.0.0"

SPEC = REPO_ROOT / "specs/reachability_spec_v1.json"
REPORT = REPO_ROOT / "gate_runs/claimb_round1_reachability_2026_08_10/reachability_report.json"


class ConstantsError(Exception):
    """A refusal."""


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path: Path) -> dict:
    try:
        return json.loads(path.read_bytes())
    except FileNotFoundError as exc:
        raise ConstantsError(f"not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ConstantsError(f"not valid JSON: {path}: {exc}") from exc


def carrier_constants(spec_path: Path, report_path: Path) -> dict:
    spec = load(spec_path)
    report = load(report_path)

    if spec.get("schema") != "reachability_spec":
        raise ConstantsError(f"{spec_path}: not a reachability_spec")
    if report.get("schema") != "reachability_report":
        raise ConstantsError(f"{report_path}: not a reachability_report")

    # The report must be OF this spec, by hash — not merely of a spec with the same name.
    spec_sha = sha256_of(spec_path)
    if report.get("spec_sha256") != spec_sha:
        raise ConstantsError(
            f"the report pins spec {report.get('spec_sha256')} but {spec_path} hashes to "
            f"{spec_sha}"
        )
    if report.get("status") != "complete":
        raise ConstantsError(
            f"the report status is {report.get('status')!r}; a carrier may only embed "
            "targets from a complete run"
        )

    order = spec["vectors"]["order"]
    if sorted(order) != list(range(64)):
        raise ConstantsError("the vector order is not a permutation of 0..63")
    train = spec["vectors"]["split"]["train_count"]
    if train != len(spec["vectors"]["split"]["train"]):
        raise ConstantsError("train_count disagrees with the train list")
    if order[:train] != spec["vectors"]["split"]["train"]:
        raise ConstantsError("the train slice is not the first train_count of the order")
    if order[train:] != spec["vectors"]["split"]["holdout"]:
        raise ConstantsError("the holdout slice is not the remainder of the order")

    luts = []
    for record, planned in zip(report["per_lut"], spec["phenotype"]["luts"]):
        if record["exhausted"]:
            raise ConstantsError(f"{record['site']}/{record['bel']} is exhausted")
        if (record["site"], record["bel"]) != (planned["site"], planned["bel"]):
            raise ConstantsError(
                f"report/spec LUT order disagrees: {record['site']}/{record['bel']} vs "
                f"{planned['site']}/{planned['bel']}"
            )
        value = int(record["target_truth_table"].split("h")[1], 16)
        if bin(value).count("1") != 32:
            raise ConstantsError(
                f"{record['site']}/{record['bel']}: target is not balanced"
            )
        luts.append(
            {
                "site": record["site"],
                "bel": record["bel"],
                "target": value,
                "base_init": int(planned["base_init"].split("h")[1], 16),
                "mutable_mask": int(planned["mutable_mask"].split("h")[1], 16),
                "attainable_ceiling": record["attainable_ceiling"],
            }
        )
    if len(luts) != len(report["per_lut"]) or len(luts) != 6:
        raise ConstantsError(f"expected six LUTs, got {len(luts)}")

    return {
        "spec": {"path": spec_path.relative_to(REPO_ROOT).as_posix(), "sha256": spec_sha},
        "report": {
            "path": report_path.relative_to(REPO_ROOT).as_posix(),
            "sha256": sha256_of(report_path),
            "report_id": report["report_id"],
        },
        "order": order,
        "train_count": train,
        "holdout_count": 64 - train,
        "luts": luts,
        "tool": TOOL_VERSION,
    }


def write_outputs(constants: dict, outdir: Path) -> list[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    header = (
        f"// generated by {constants['tool']} — do not edit\n"
        f"// spec   {constants['spec']['path']} {constants['spec']['sha256']}\n"
        f"// report {constants['report']['path']} {constants['report']['sha256']}\n"
    )

    order_path = outdir / "carrier_vector_order.hex"
    order_path.write_text(
        header + "".join(f"{v:02x}\n" for v in constants["order"]), encoding="utf-8"
    )

    targets_path = outdir / "carrier_targets.hex"
    targets_path.write_text(
        header + "".join(f"{l['target']:016x}\n" for l in constants["luts"]),
        encoding="utf-8",
    )

    # The base INIT the carrier must instantiate, one line per LUT in the frozen order.
    init_path = outdir / "carrier_base_init.vh"
    lines = [header]
    for index, lut in enumerate(constants["luts"]):
        lines.append(
            f"localparam [63:0] BASE_INIT_{index} = 64'h{lut['base_init']:016X}; "
            f"// {lut['site']}/{lut['bel']}\n"
        )
    init_path.write_text("".join(lines), encoding="utf-8")

    manifest = outdir / "carrier_constants.json"
    manifest.write_text(json.dumps(constants, indent=2) + "\n", encoding="utf-8")
    return [order_path, targets_path, init_path, manifest]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--spec", type=Path, default=SPEC)
    ap.add_argument("--report", type=Path, default=REPORT)
    ap.add_argument("--outdir", type=Path, default=REPO_ROOT / "vivado/carrier/generated")
    args = ap.parse_args()

    try:
        constants = carrier_constants(args.spec.resolve(), args.report.resolve())
    except ConstantsError as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2

    written = write_outputs(constants, args.outdir)
    print(f"{args.outdir}: {len(constants['order'])} vectors, {len(constants['luts'])} targets")
    for lut in constants["luts"]:
        print(f"  {lut['site']}/{lut['bel']:6s} target 64'h{lut['target']:016X} "
              f"ceiling {lut['attainable_ceiling']}")
    print(f"  train {constants['train_count']} / holdout {constants['holdout_count']}")
    for path in written:
        print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
