"""Review the first real B2Q archive without touching the board or live manifest.

The S2 candidate is made in memory and verified in a fresh process from a temporary
file. Its timestamp-dependent digest is diagnostic, not a future ruling binding.
"""
import collections
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "host"))
import b2_manifest as bm
import b2_runner as rn
import b1_qualification as bq

rn.inst.bind()
import l5_notary as wire
from validators import records

ev = Path("evidence/b2/b2q_17A6_2026-09-14-01")
assert Path.cwd() == ROOT, "Run this script from the repository root"
digest = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()
before = bm.MANIFEST.read_bytes()
m = json.loads(before)
assert before == (ev / "manifest_at_run.json").read_bytes()
assert digest(bm.MANIFEST) == "8699767744b8f7c1f68a49252acddd91af0e9d1732a0a772476fc0f257949b35"
out = {"head": subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip(),
       "evidence": str(ev), "archive_files": {p.name: digest(p) for p in sorted(ev.iterdir()) if p.is_file()},
       "s1_verify": bm.verify(m)}
assert len(out["archive_files"]) == 15
out["readjudication"] = rn.readjudicator(m)(ev, m)
assert out["readjudication"] == json.loads((ev / "adjudication.json").read_text())
assert out["readjudication"]["outcome"] == "PASS"
assert bm.summary_findings(ev) == []
summary = json.loads((ev / "summary.json").read_text())
timeline = json.loads((ev / "timeline.json").read_text())
log = json.loads((ev / "run_log.json").read_text())
expected_rulings = {
    "whole_of_run": "24e732d71c679ba86188408b4da8f0619c69dd8119b7512d887663ae2e17d1b0",
    "provisioning": "c56f9401d829b8b52f4d695b3f0d758bbc505b86f2a126f973b12572e51a552a"}
rulings = {}
for role, want in expected_rulings.items():
    raw, ruling = bq.read_archived_ruling(ev / bq.RULING_FILES[role])
    assert hashlib.sha256(raw).hexdigest() == want
    rulings[role] = ruling
out["issued_ruling_bytes_match"] = expected_rulings
boundary_path = Path("evidence/b2/principal_boundary_2026-09-14-01.json")
boundary = json.loads(boundary_path.read_text())
assert digest(boundary_path) == rulings["whole_of_run"]["boundary_record_observed_at_issue"]["sha256"]
first_wall = timeline["frames"][0]["t_wall"]
records.boundary_established(boundary, first_wall)
out["historical_boundary"] = {"sha256": digest(boundary_path),
    "age_at_first_frame_s": first_wall - boundary["at"], "key_id": boundary["key_id"],
    "note": "Recorded boundary checked at the archived session time; no new permission probe."}
raw_lines = (ev / "console.log").read_text().splitlines()
good, controls = collections.Counter(), []
for index, line in enumerate(raw_lines):
    if not line.startswith("P3L5 "):
        continue
    try:
        frame = wire.parse_line(line)
        good[frame["type"]] += 1
    except wire.CrcError:
        header = line.split(" ")[:4]
        assert header[1:3] in (["SIGNREQ", "1"], ["REC", "1"])
        later = next(x for x in raw_lines[index + 1:] if x.split(" ")[:4] == header)
        wire.parse_line(later)
        assert line.rsplit(" ", 1)[0] == later.rsplit(" ", 1)[0]
        controls.append({"line": index + 1, "type": header[1], "seq": 1,
                         "same_body_as_valid_retransmission": True,
                         "bad_crc": line.rsplit(" ", 1)[1], "valid_crc": later.rsplit(" ", 1)[1]})
assert len(controls) == 2 and {c["type"] for c in controls} == {"REC", "SIGNREQ"}
assert dict(good) == summary["l6"]["expected_frames"]["by_type"]
assert sum(good.values()) == 543
assert timeline["crc_dropped"] == 2 and timeline["bad_frames"] == 0 and timeline["fragments"] == []
assert log["app_identity"]["rec_retry_control"] and log["app_identity"]["sign_retry_control"]
out["transport"] = {"crc_valid_frames": dict(good), "crc_valid_total": sum(good.values()),
    "crc_controls": controls, "non_control_crc_drops": 0, "host_budget": summary["crc_budget"],
    "board_summary": log["session_summary"],
    "note": "Host-requested controls are generated by the firmware; board and host counters describe opposite receive directions."}
s2 = bm.qualify(m, ev, readjudicate=rn.readjudicator(m))
changed = sorted(k for k in s2 if s2[k] != m[k])
assert changed == ["calibration", "history", "qualification", "qualified", "status"]
assert s2["plan"] is None
out["s2_preview"] = {"changed_fields": changed, "calibration": s2["calibration"],
    "record_file_count": len(s2["qualification"]["files"]),
    "derived_split_not_pinned": bm.canonical_plan(s2)["session_split"]}
with tempfile.TemporaryDirectory(prefix="b2q_s2_review_") as tmp:
    path = Path(tmp) / "candidate.json"
    path.write_text(bm.render(s2))
    code = """import json,sys
sys.path.insert(0, 'host')
import b2_manifest as bm,b2_runner as rn
m=json.load(open(sys.argv[1]))
r=bm.verify(m,readjudicate=rn.readjudicator(m))
assert r['stage']=='S2' and r['qualified'] and r['refusal'] is None
print(json.dumps(r))
"""
    out["fresh_process_s2_verify"] = json.loads(subprocess.check_output(
        [sys.executable, "-B", "-c", code, str(path)], cwd=ROOT, text=True))
assert bm.MANIFEST.read_bytes() == before
assert {p.name: digest(p) for p in sorted(ev.iterdir()) if p.is_file()} == out["archive_files"]
out["production_manifest_and_archive_unchanged"] = True
out["review_outcome"] = "PASS"
print(json.dumps(out, indent=2, sort_keys=True))
